document the VAL_1 routine that got implemented
X16Community/x16-docs pull request #106
Opened 2023-12-01 22:39 UTC by irmen

PR for rom to implement it is here https://github.com/X16Community/x16-rom/pull/231

Setting this PR as draft until above gets approved.

2023-12-18 21:19 UTC, mooinglemur requested changes
Please add a note somewhere to indicate that VAL_1 requires intact BASIC zeropage

2023-12-18 21:30 UTC, irmen commented
Yup, I'll add some of the relevant discourse about this subject.

2023-12-29 00:39 UTC, irmen commented
@mooinglemur  added the caveat about zero page usage.

2023-12-30 01:12 UTC, mooinglemur approved these changes

2023-12-30 01:13 UTC, merged