Update opcodes doc to include warning about possible 816 use
X16Community/x16-docs pull request #123
Opened 2024-01-07 19:45 UTC by m00dawg

Update opcodes doc to include warning about possible 816 use

2024-01-08 06:03 UTC, tomxp411 requested changes
Good additions. Part of me thinks "too soon", but there's no down side to calling out the 65C816 differences, even if the '816 doesn't happen. 

If you will fix the Table of contents to to be consistent with the get and set time functions, I'll pass it.

2024-01-08 06:03 UTC, tomxp411 commented on X16 Reference - 04 - KERNAL.md
> +Communication registers: r0, r1, r2, r3L
Please double check the table of contents (pg 43 on the PDF generated from this PR). Says r3 there, not r3L.

2024-01-08 22:22 UTC, m00dawg commented on X16 Reference - 04 - KERNAL.md
> +Communication registers: r0, r1, r2, r3L
that's 100%  a typo. Funky I don't even know how I managed to get that in there since I poured over this PR. I'll fix post haste.

2024-01-08 22:42 UTC, m00dawg commented
@tomxp411 added a manual footnote to get that working on the PDF. It works for mk-docs, github, and PDF so let me know what you think  there. I think I fixed the other issues? If not definitely let me know if I hozed something. I didn't quite follow the mention of the TOC but I did fix the funky `L` additions.

2024-01-09 00:29 UTC, tomxp411 approved these changes
thanks for the fix. I'm going to sign off on this, even if I haven't checked every reference.  :)

2024-01-09 00:29 UTC, merged