fix ROL, ROR, ASL, LSR errors
X16Community/x16-docs pull request #146
Opened 2024-02-08 06:33 UTC by tomxp411

This fixes the description for the rotate/shift instructions. The original descriptions were incorrect.

2024-02-09 02:17 UTC, m00dawg approved these changes

2024-02-09 18:17 UTC, mooinglemur commented
The GitHub flavored markdown way of doing explicit line breaks is two spaces at the end of the line.  This is done throughout the rest of the Programmer's Reference Guide.  Is there any reason to use HTML instead?

I think the PDF generation works fine with GFM line breaks.

2024-02-10 05:46 UTC, tomxp411 commented
That's just the way I wrote the code generator; I can easily change it.

2024-02-29 21:46 UTC, mooinglemur requested changes

2024-03-01 08:23 UTC, mooinglemur approved these changes

2024-03-01 08:23 UTC, merged